apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::221082216149:user/MurathanErgin
      username: MurathanErgin
      groups:
        - system:masters
